"""Add generation and types to Pokemon model

Revision ID: 846d6433376d
Revises: 
Create Date: 2024-10-19 14:18:11.214737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846d6433376d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generation', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sprite_filename', sa.String(length=200), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('sprite_filename')
        batch_op.drop_column('generation')

    # ### end Alembic commands ###
